name: "Deploy"
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    name: "Deploy GH page"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: "Installing project dependencies"
        run: |
          npm ci
      - name: "Generating static website"
        run: |
          npm run generate
      - name: "Configuring SSH"
        env:
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"
      - name: "Update github page"
        env:
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
        run: |
          git config --global user.email "evbot@eventline.net"
          git config --global user.name "evbot"
          git remote set-url origin git@github.com:exograd/status-page.git
          echo "status.eventline.net" > dist/CNAME
          npm run deploy
